UPDATE wishlists SET client_id=2 WHERE client_id=33;
UPDATE queue SET client_id=2 WHERE client_id=33;
DELETE FROM client_shares WHERE client_id=33;
DELETE FROM clients WHERE id=33;
UPDATE wishlists SET client_id=14 WHERE client_id=22;
UPDATE queue SET client_id=14 WHERE client_id=22;
DELETE FROM client_shares WHERE client_id=22;
DELETE FROM clients WHERE id=22;
UPDATE wishlists SET client_id=10 WHERE client_id=26;
UPDATE queue SET client_id=10 WHERE client_id=26;
DELETE FROM client_shares WHERE client_id=26;
DELETE FROM clients WHERE id=26;
UPDATE wishlists SET client_id=4 WHERE client_id=32;
UPDATE queue SET client_id=4 WHERE client_id=32;
DELETE FROM client_shares WHERE client_id=32;
DELETE FROM clients WHERE id=32;
UPDATE wishlists SET client_id=13 WHERE client_id=23;
UPDATE queue SET client_id=13 WHERE client_id=23;
DELETE FROM client_shares WHERE client_id=23;
DELETE FROM clients WHERE id=23;
UPDATE wishlists SET client_id=8 WHERE client_id=28;
UPDATE queue SET client_id=8 WHERE client_id=28;
DELETE FROM client_shares WHERE client_id=28;
DELETE FROM clients WHERE id=28;
UPDATE wishlists SET client_id=7 WHERE client_id=29;
UPDATE queue SET client_id=7 WHERE client_id=29;
DELETE FROM client_shares WHERE client_id=29;
DELETE FROM clients WHERE id=29;
UPDATE wishlists SET client_id=6 WHERE client_id=30;
UPDATE queue SET client_id=6 WHERE client_id=30;
DELETE FROM client_shares WHERE client_id=30;
DELETE FROM clients WHERE id=30;
UPDATE wishlists SET client_id=9 WHERE client_id=27;
UPDATE queue SET client_id=9 WHERE client_id=27;
DELETE FROM client_shares WHERE client_id=27;
DELETE FROM clients WHERE id=27;
UPDATE wishlists SET client_id=11 WHERE client_id=25;
UPDATE queue SET client_id=11 WHERE client_id=25;
DELETE FROM client_shares WHERE client_id=25;
DELETE FROM clients WHERE id=25;
UPDATE wishlists SET client_id=12 WHERE client_id=24;
UPDATE queue SET client_id=12 WHERE client_id=24;
DELETE FROM client_shares WHERE client_id=24;
DELETE FROM clients WHERE id=24;
UPDATE wishlists SET client_id=15 WHERE client_id IN (21,34);
UPDATE queue SET client_id=15 WHERE client_id IN (21,34);
DELETE FROM client_shares WHERE client_id IN (21,34);
DELETE FROM clients WHERE id IN (21,34);
INSERT OR IGNORE INTO client_shares (client_id, agent_id) VALUES (2,8),(14,8),(10,8),(4,8),(13,8),(8,8),(7,8),(6,8),(9,8),(11,8),(12,8),(15,8);
UPDATE queue SET status='expired', decided_at=datetime('now') WHERE status='pending' AND json_extract(lot_json,'$.auction_date') < datetime('now');